In [116]:
import numpy as np
import pandas as pd


from matplotlib import pyplot as plt
import seaborn as sns


%matplotlib inline

In [117]:
location = "DC_Properties.csv"
df = pd.read_csv(location)

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [118]:
dupe = df.duplicated() #creates list of True/False values
df[dupe] #shows rows where duplicated is True

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [119]:
#drops duplicate rows, default is to keep first observation
df.drop_duplicates()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
5,5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
6,6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,...,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,...,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
11,11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,NaN,...,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
14,14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
16,16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
17,17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,...,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
18,18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,...,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
20,20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
21,21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,...,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
22,22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,...,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
23,23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,...,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
24,24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,...,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
25,25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,...,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
27,27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,...,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
28,28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,...,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
29,29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,...,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,158927,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158938,158938,2,0,Warm Cool,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158939,158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158940,158940,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158944,158944,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [120]:
df.describe()

,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,USECODE,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,X,Y
count,158957.000000,158957.000000,158957.000000,106696.000000,158957.000000,158957.000000,158686.000000,80928.000000,158957.000000,106652.000000,...,158957.000000,158957.000000,52261.000000,52261.000000,158956.000000,158956.000000,158956.000000,158956.000000,158720.000000,158720.000000
mean,79478.000000,1.810678,0.458237,1.198039,6.187736,2.732506,1941.987579,1998.243537,1963.718024,2.091793,...,14.252999,2473.282158,2371.544249,888.834542,20012.694563,38.914854,-77.016676,5348.216324,-77.016712,38.914846
std,45887.077707,0.976396,0.587571,0.596924,2.618165,1.358864,33.640234,16.575786,24.923150,2.933323,...,3.725736,5059.046023,1114.272364,420.185822,15.627084,0.031723,0.040938,3369.645953,0.040933,0.031682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1754.000000,20.000000,1800.000000,0.000000,...,11.000000,0.000000,1001.000000,0.000000,20001.000000,38.819731,-77.113909,100.000000,-77.113135,38.820576
25%,39739.000000,1.000000,0.000000,1.000000,4.000000,2.000000,1918.000000,1985.000000,1954.000000,2.000000,...,11.000000,697.000000,1501.000000,616.000000,20007.000000,38.895425,-77.042892,2102.000000,-77.042894,38.895432
50%,79478.000000,2.000000,0.000000,1.000000,6.000000,3.000000,1937.000000,2004.000000,1963.000000,2.000000,...,13.000000,1649.000000,2265.000000,783.000000,20011.000000,38.915337,-77.019596,5201.000000,-77.019581,38.915229
75%,119217.000000,2.000000,1.000000,1.000000,7.000000,3.000000,1960.000000,2010.000000,1975.000000,2.000000,...,17.000000,3000.000000,2910.000000,1060.000000,20018.000000,38.936075,-76.988626,8302.000000,-76.988842,38.936077
max,158956.000000,14.000000,11.000000,6.000000,48.000000,24.000000,2019.000000,2019.000000,2018.000000,826.000000,...,117.000000,942632.000000,5621.000000,8553.000000,20392.000000,38.995540,-76.909758,11100.000000,-76.910511,38.993646

In [121]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [122]:
df.groupby(['PRICE','BATHRM','BEDRM','STYLE','FULLADDRESS','WARD'])

In [123]:
nf = df[['PRICE','BATHRM','BEDRM','STYLE','FULLADDRESS','WARD']]

In [124]:
nf.loc[nf['PRICE']<=850000]

           PRICE  BATHRM  BEDRM    STYLE                   FULLADDRESS    WARD
19      592250.0       3      3  2 Story          1735 SWANN STREET NW  Ward 2
20       33232.0       3      5  3 Story              1441 Q STREET NW  Ward 2
25       20000.0       1      4  2 Story              1451 Q STREET NW  Ward 2
27      703700.0       3      3  3 Story       1456 CORCORAN STREET NW  Ward 2
32      130500.0       2      2  3 Story       1446 CORCORAN STREET NW  Ward 2
37      339500.0       2      4  3 Story       1432 CORCORAN STREET NW  Ward 2
45      450000.0       3      5  3 Story       1414 CORCORAN STREET NW  Ward 2
46      846000.0       3      4  3 Story       1412 CORCORAN STREET NW  Ward 2
48      348500.0       2      3  3 Story       1421 CORCORAN STREET NW  Ward 2
50      849000.0       2      3  3 Story       1429 CORCORAN STREET NW  Ward 2
54      390000.0       1      2  3 Story       1443 CORCORAN STREET NW  Ward 2
55      772500.0       3      3  2 Story       1445 CORCORAN STREET NW  Ward 2
58      499000.0       1      1  2 Story          1508 SWANN STREET NW  Ward 2
59      216000.0       2      2  2 Story          1506 SWANN STREET NW  Ward 2
61      636090.0       3      3  2 Story              1503 S STREET NW  Ward 2
65      380000.0       3      3  3 Story          1523 SWANN STREET NW  Ward 2
69      463000.0       3      4  3 Story              1503 R STREET NW  Ward 2
71      682500.0       2      3  2 Story           1909 17TH STREET NW  Ward 2
73      745000.0       2      2  2 Story           1913 17TH STREET NW  Ward 2
76      848500.0       2      4  2 Story  1920 NEW HAMPSHIRE AVENUE NW  Ward 2
77      277000.0       2      3  2 Story  1918 NEW HAMPSHIRE AVENUE NW  Ward 2
92      360000.0       2      4  2 Story              2150 F STREET NW  Ward 2
97      770000.0       4      4  4 Story           1703 21ST STREET NW  Ward 2
101     750000.0       4      5  3 Story              2011 R STREET NW  Ward 2
132     282777.0       1      3  2 Story          1743 SWANN STREET NW  Ward 2
133     715000.0       3      3  2 Story          1745 SWANN STREET NW  Ward 2
136     229161.0       1      3  2 Story          1751 SWANN STREET NW  Ward 2
148     795000.0       2      2  2 Story       1806 CORCORAN STREET NW  Ward 2
150     799000.0       2      2  2 Story       1810 CORCORAN STREET NW  Ward 2
156     200000.0       2      3  3 Story        1700 FLORIDA AVENUE NW  Ward 1
...          ...     ...    ...      ...                           ...     ...
158912  185000.0       2      2      NaN                           NaN  Ward 6
158914  549000.0       2      2      NaN                           NaN  Ward 6
158915  441000.0       1      1      NaN                           NaN  Ward 6
158916  409000.0       1      1      NaN                           NaN  Ward 6
158918  839000.0       2      2      NaN                           NaN  Ward 6
158924  269000.0       1      2      NaN                           NaN  Ward 6
158926  385000.0       1      2      NaN                           NaN  Ward 6
158928  632400.0       2      2      NaN                           NaN  Ward 6
158929  574000.0       2      2      NaN                           NaN  Ward 6
158930  365000.0       2      2      NaN                           NaN  Ward 6
158931  405000.0       2      2      NaN                           NaN  Ward 6
158932  505000.0       2      2      NaN                           NaN  Ward 6
158933  520000.0       2      2      NaN                           NaN  Ward 6
158934  499900.0       1      1      NaN                           NaN  Ward 6
158935  451000.0       1      1      NaN                           NaN  Ward 6
158936  564900.0       1      1      NaN                           NaN  Ward 6
158938  660000.0       2      4      NaN                           NaN  Ward 6
158939  380000.0       1      2      NaN                           NaN  Ward 6
158943  539000.0       2      2      NaN                           NaN  Ward 6
158945  450000.0       1      1      NaN                           NaN  Ward 6
158946  485355.0       1      2      NaN                           NaN  Ward 6
158947  320000.0       2      2      NaN                           NaN  Ward 6
158948  460000.0       2      2      NaN                           NaN  Ward 6
158949  550000.0       1      1      NaN                           NaN  Ward 6
158950  635000.0       3      3      NaN                           NaN  Ward 6
158951  389000.0       3      3      NaN                           NaN  Ward 6
158952  399900.0       1      1      NaN                           NaN  Ward 6
158953  416000.0       1      2      NaN                           NaN  Ward 6
158954  600000.0       2      2      NaN                           NaN  Ward 6
158955  215100.0       1      0      NaN                           NaN  Ward 6

[84776 rows x 6 columns]

In [125]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [126]:
bins = [0,10000,300000, 400000,500000,600000,700000,80000000]
group_names = ['Poverty level','Working poor','Working class',
            'Middle class','New Money','Upper class','One Percent']
nf['Affordability'] = pd.cut(nf['PRICE'], bins, labels=group_names)
nf.head(10)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,PRICE,BATHRM,BEDRM,STYLE,FULLADDRESS,WARD,Affordability
0,1095000.0,4,4,3 Story,1748 SWANN STREET NW,Ward 2,One Percent
1,NaN,3,5,3 Story,1746 SWANN STREET NW,Ward 2,NaN
2,2100000.0,3,5,3 Story,1744 SWANN STREET NW,Ward 2,One Percent
3,1602000.0,3,5,3 Story,1742 SWANN STREET NW,Ward 2,One Percent
4,NaN,2,3,3 Story,1804 NEW HAMPSHIRE AVENUE NW,Ward 2,NaN
5,1950000.0,3,5,4 Story,1709 S STREET NW,Ward 2,One Percent
6,NaN,1,2,2 Story,1769 SWANN STREET NW,Ward 2,NaN
7,1050000.0,3,4,3 Story,1746 1/2 T STREET NW,Ward 2,One Percent
8,1430000.0,3,3,2 Story,1727 SWANN STREET NW,Ward 2,One Percent
9,NaN,1,2,2 Story,1733 SWANN STREET NW,Ward 2,NaN

In [127]:
nf.groupby(['Affordability','STYLE']).mean()

                                      PRICE    BATHRM     BEDRM
Affordability STYLE
Poverty level 1 Story          6.500000e+03  1.500000  2.500000
              1.5 Story Fin             NaN       NaN       NaN
              1.5 Story Unfin           NaN       NaN       NaN
              2 Story          3.406622e+03  1.800000  3.177778
              2.5 Story Fin    4.156000e+03  2.000000  4.000000
              2.5 Story Unfin           NaN       NaN       NaN
              3 Story          8.126250e+02  3.000000  5.000000
              3.5 Story Fin             NaN       NaN       NaN
              3.5 Story Unfin           NaN       NaN       NaN
              4 Story                   NaN       NaN       NaN
              4.5 Story Fin             NaN       NaN       NaN
              4.5 Story Unfin           NaN       NaN       NaN
              Bi-Level                  NaN       NaN       NaN
              Default                   NaN       NaN       NaN
              Outbuildings              NaN       NaN       NaN
              Split Foyer               NaN       NaN       NaN
              Split Level               NaN       NaN       NaN
              Vacant                    NaN       NaN       NaN
Working poor  1 Story          1.767039e+05  1.521739  2.742164
              1.5 Story Fin    1.806101e+05  1.551069  3.019002
              1.5 Story Unfin  1.632739e+05  1.434783  2.826087
              2 Story          1.769366e+05  1.639452  3.038010
              2.5 Story Fin    2.043221e+05  2.129534  3.813472
              2.5 Story Unfin  1.962150e+05  1.743902  3.426829
              3 Story          1.961465e+05  2.515730  3.840449
              3.5 Story Fin    1.474842e+05  2.769231  3.307692
              3.5 Story Unfin  1.950000e+05  3.000000  4.000000
              4 Story          1.816444e+05  3.000000  3.555556
              4.5 Story Fin    6.778075e+04  1.750000  3.000000
              4.5 Story Unfin  2.999000e+05  3.000000  3.000000
...                                     ...       ...       ...
Upper class   3 Story          6.545981e+05  2.799505  3.955446
              3.5 Story Fin    6.633333e+05  4.333333  5.000000
              3.5 Story Unfin  6.257200e+05  3.000000  4.000000
              4 Story          6.623666e+05  4.000000  5.111111
              4.5 Story Fin             NaN       NaN       NaN
              4.5 Story Unfin           NaN       NaN       NaN
              Bi-Level         6.573333e+05  2.666667  3.000000
              Default          6.852860e+05  3.000000  4.000000
              Outbuildings              NaN       NaN       NaN
              Split Foyer               NaN       NaN       NaN
              Split Level      6.516295e+05  2.727273  3.909091
              Vacant                    NaN       NaN       NaN
One Percent   1 Story          1.154222e+06  2.729483  3.537994
              1.5 Story Fin    1.054636e+06  2.826772  3.814961
              1.5 Story Unfin  1.233833e+06  2.933333  3.133333
              2 Story          1.031411e+06  2.614596  3.609216
              2.5 Story Fin    1.481729e+06  3.520016  4.723379
              2.5 Story Unfin  1.080930e+06  2.764228  3.967480
              3 Story          1.388816e+06  3.282809  4.395297
              3.5 Story Fin    1.676623e+06  3.389831  4.372881
              3.5 Story Unfin  3.658167e+06  4.333333  6.333333
              4 Story          1.806447e+06  3.657895  4.510526
              4.5 Story Fin    2.500000e+06  4.000000  4.000000
              4.5 Story Unfin           NaN       NaN       NaN
              Bi-Level         1.029167e+06  2.666667  3.666667
              Default          2.385833e+06  2.000000  2.666667
              Outbuildings              NaN       NaN       NaN
              Split Foyer      9.295000e+05  3.000000  4.000000
              Split Level      9.863201e+05  3.063492  3.873016
              Vacant           9.600000e+05  3.000000  4.500000

[126 rows x 3 columns]